name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository (pastikan build.gradle Anda sudah ter-commit di sini)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Opsional: Tampilkan struktur file untuk memastikan file-file penting ada
      - name: List repository files
        run: ls -la

      - name: List files in android directory
        run: ls -la android

      # Jika belum ada Gradle Wrapper, langkah ini akan menghasilkannya dengan Gradle 8.0-all.
      # Jika wrapper sudah ada dan sudah terupdate, langkah ini bisa dilewati atau dibiarkan.
      - name: Generate Gradle Wrapper (if needed)
        working-directory: android
        run: gradle wrapper --gradle-version 8.0 --distribution-type all

      # Pastikan gradlew memiliki izin eksekusi
      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      # Build aplikasi (assembleDebug akan mengambil dependency dari Maven Central sesuai konfigurasi di build.gradle)
      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      # Upload APK sebagai artifact agar bisa diunduh
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
