name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Opsional: Tampilkan struktur file untuk verifikasi
      - name: List repository files
        run: ls -la

      - name: List files in android directory
        run: ls -la android

      # Generate (atau perbarui) Gradle Wrapper di direktori android (bukan subproyek)
      - name: Generate Gradle Wrapper
        working-directory: android
        run: gradle wrapper --gradle-version 8.0 --distribution-type all

      # Pastikan gradlew memiliki izin eksekusi di direktori android
      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      # Jalankan build untuk subproyek test-app-local-dependency dari direktori android
      - name: Build Debug APK for test-app-local-dependency
        working-directory: android
        run: ./gradlew :test-app-local-dependency:assembleDebug

      # Upload file APK yang dihasilkan dari subproyek test-app-local-dependency
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: test-app-local-dependency/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
