name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle (needed for generating wrapper)
        run: |
          sudo apt-get update
          sudo apt-get install gradle -y

      # Opsional: List file-file repository untuk memastikan struktur direktori
      - name: List repository files
        run: ls -la

      # Misalnya, jika proyek Android Anda berada di folder "android"
      - name: List files in android directory
        run: ls -la android

      - name: Generate (or Update) Gradle Wrapper
        working-directory: android
        run: gradle wrapper --gradle-version 7.6

      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
