name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Opsional: List file-file repository untuk verifikasi struktur
      - name: List repository files
        run: ls -la

      - name: List files in android directory
        run: ls -la android

      # Generate (atau perbarui) Gradle Wrapper dari direktori android (proyek utama)
      - name: Generate Gradle Wrapper
        working-directory: android
        run: gradle wrapper --gradle-version 8.0 --distribution-type all

      # Pastikan file gradlew memiliki izin eksekusi
      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      # Bangun APK untuk subproyek test-app-local-dependency dengan menjalankan task assembleDebug
      - name: Build Debug APK for test-app-local-dependency
        working-directory: android
        run: ./gradlew :test-app-local-dependency:assembleDebug

      # Langkah tambahan: List isi direktori output APK untuk memastikan file APK telah dihasilkan
      - name: List APK output directory
        working-directory: android/test-app-local-dependency/build/outputs/apk/debug
        run: ls -la

      # Upload file APK sebagai artifact; path disesuaikan dengan lokasi output build
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/test-app-local-dependency/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
